# Generated by Django 4.1.7 on 2023-06-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio_note',
            name='audio',
            field=models.FileField(null=True, upload_to='audio/'),
        ),
    ]
