# Generated by Django 4.1.7 on 2023-06-26 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_audio_note_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio_note',
            name='user',
        ),
    ]
