# Generated by Django 4.1.7 on 2023-06-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_remove_audio_note_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='neme',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='audio_note',
            name='audio_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=30),
        ),
    ]
