# Generated by Django 4.1.7 on 2023-06-27 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0005_alter_audio_note_audio_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio_note',
            name='user',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='note.users'),
            preserve_default=False,
        ),
    ]
