# Generated by Django 4.1.7 on 2023-04-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=12)),
                ('desc', models.TextField()),
                ('operator', models.CharField(choices=[('bl', 'Banglalink'), ('rb', 'Robi'), ('gp', 'Grameenphone'), ('tt', 'Taletalk')], max_length=15)),
                ('date', models.DateField()),
            ],
        ),
    ]
